import type { Metadata } from 'next';
// Assuming Geist and Geist_Mono are local or custom fonts for this example
import { Geist, Geist_Mono } from 'next/font/google';
import { Manrope } from 'next/font/google';
import './globals.css';
import Script from 'next/script';

// 1. Configure Geist fonts (unchanged)
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// 2. Configure Manrope font (unchanged)
const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-manrope',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} antialiased`}>
        {children}{/* Load MediaPipe scripts from CDN */}
        <Script src="https://cdn.jsdelivr.net/npm/@mediapipe/camera_utils/camera_utils.js" crossOrigin="anonymous" />
        <Script src="https://cdn.jsdelivr.net/npm/@mediapipe/control_utils/control_utils.js" crossOrigin="anonymous" />
        <Script src="https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils/drawing_utils.js" crossOrigin="anonymous" />
        <Script src="https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose.js" crossOrigin="anonymous" />
        {/* Load your local script AFTER the dependencies */}
        <Script src="/script.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
